version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
  web:
    image: dhis2/core:2.33.0
    volumes:
    - /root/dhis_docker/conf/dhis.conf:/DHIS2_home/dhis.conf
    ports:
    - "8081:8080"
    depends_on:
    - db