version: '3'
services:
    dhis:
        image: dhis2/core:2.37.6-tomcat-8.5.34-jre8-alpine
        ports:
            - "8000:8080"
        volumes:
            - C:\Users\jecob\dhis2-docker\conf\dhis.conf:/DHIS2_home/dhis.conf
        environment:
            - WAIT_FOR_DB_CONTAINER=db34:5432 -t 0
            - _JAVA_OPTIONS=-Xmx500m -Xms500m -XX:MaxPermSize=500m -XX:PermSize=300m

        depends_on:
            - db34
    db34:
        image: mdillon/postgis:10-alpine
        ports:
            - "3432:5432"
        volumes:
            - C:\Users\jecob\dhis2-docker\db\:/docker-entrypoint-initdb.d/
        command: postgres -c max_locks_per_transaction=96
        environment:
            - POSTGRES_PASSWORD=dhis
            - POSTGRES_USER=dhis
            - POSTGRES_DB=dhis2

