version: '3'
services:
    dhis:
        image: tomcat:8.5-jdk8-temurin
        ports:
            - "8888:8080"
        volumes:
            - /home/jaime/uio/github/jaboto/dhis2-docker/composers/ownWAR/conf/dhis.conf:/opt/dhis2/dhis.conf
            - /home/jaime/uio/github/jaboto/dhis2-docker/composers/ownWAR/dhis.war:/usr/local/tomcat/webapps/ROOT.war
        environment:
            - WAIT_FOR_DB_CONTAINER=db:5432 -t 0
        depends_on:
            - db
    db:
        image: mdillon/postgis:10-alpine
        ports:
            - "3732:5432"
        volumes:
            - /home/jaime/uio/dbs/2.37/:/docker-entrypoint-initdb.d/
        command: postgres -c max_locks_per_transaction=96
        environment:
            - POSTGRES_PASSWORD=dhis
            - POSTGRES_USER=dhis
            - POSTGRES_DB=dhis2
